# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 02:26
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160801_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Zipcode',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
    ]
