# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 01:51
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20160801_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='city',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zipcode',
            name='dong',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zipcode',
            name='gu',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zipcode',
            name='road',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=models.CharField(max_length=7, validators=[blog.validators.ZipcodeValidator(True)]),
        ),
    ]
