# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 01:58
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20160803_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipcode',
            old_name='code',
            new_name='zipcode',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
    ]
